# This action will run rst2pdf to generate a PDF from the latest docs.
#
name: rst2pdf

on:
  push:
    branches: [ update ]
    paths-ignore:
      - 'pdf/**'

permissions:
  contents: write # for Git to git push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install rst2pdf
      run: |
        pip install --user rst2pdf

    - uses: actions/checkout@v3

    - name: Clone docs
      run: |
        git config --global user.email 'ebpf-docs@users.noreply.github.com'
        git config --global user.name 'Github Action'
        git clone --branch pdf https://github.com/ebpffoundation/ebpf-docs.git pdf

    - name: Build PDF
      run: |
        rst2pdf rst/instruction-set.rst pdf/instruction-set.pdf

    - name: Checkin PDF
      run: |
        cd pdf
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -s -m "Updated PDF"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ebpffoundation/ebpf-docs.git
          git push
        fi
